# Generated by Django 5.0.7 on 2024-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkewStarh1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SkewStarP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
