# Generated by Django 5.0.7 on 2024-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subttle',
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
