# Generated by Django 5.0.7 on 2024-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_service_subttle_service_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
