# Generated by Django 5.0.7 on 2024-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('title2', models.CharField(max_length=50)),
                ('span1', models.CharField(max_length=20)),
                ('span2', models.TextField(null=True)),
            ],
        ),
    ]
