# Generated by Django 5.0.7 on 2024-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_blogtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
