# Generated by Django 5.0.7 on 2024-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(null=True, upload_to='profile_imagws/'),
        ),
    ]
