# Generated by Django 5.0.7 on 2024-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
